config/routes.rb
Rails.application.routes.draw do

  ActiveAdmin.routes(self)

  devise_for :users
  get '/about', to: 'pages#about' #this makes the file path '/about' instead of 'pages/about'

  get '/contact', to: 'pages#contact'

  get 'welcome/index'

  resources :articles do
    resources :comments
  end

  root 'articles#index'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)

    if user.role? :administrator
        can :manage, :all
    else
        can :read, :all
    end
  end

end

app/models/article.rb
class Article < ActiveRecord::Base
	has_many :comments, dependent: :destroy
	validates :title, presence: true,
					  length: {minimum: 5}
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article
  validates :commenter, presence: true
  validates :body, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable

  # def role?(base_role)
  #     role.present? && ROLES.index(base_role.to_s) <= ROLES.index(role)
  # end

  def role?(r)
      role.include? r.to_s
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  # rescue_from CanCan::AccessDenied do |exception|
  #   redirect_to root_url, :alert => exception.message
  # end

  def authenticate_active_admin_user!
  	  authenticate_user!
  	  unless current_user.role?(:administrator)
  	  	  flash[:alert] = "You are not authorized to access this resource!"
  	  	  redirect_to root_path
  	  end
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  # load_and_authorize_resource

  before_action :authenticate_user!, except: [:index, :show]
	def index
		@articles = Article.all.order('created_at DESC').paginate(:page => params[:page], :per_page => 4)
	end

	def show
		@article = Article.find(params[:id])
	end

	def new
		@article = Article.new
	end

	def edit
		@article = Article.find(params[:id])
	end

	def create
		@article = Article.new(article_params)

		if @article.save
			redirect_to @article
		else
			render 'new'
		end
	end

	def update
	  @article = Article.find(params[:id])

	  if @article.update(article_params)
	    redirect_to @article
	  else
	    render 'edit'
	  end
	end

	def destroy
		@article = Article.find(params[:id])
		@article.destroy

		redirect_to articles_path
	end

	private
		def article_params
			params.require(:article).permit(:title, :text)
		end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  # load_and_authorize_resource

  def new
    @comment = Comment.new
  end

	def create
	    @article = Article.find(params[:article_id])
	    @comment = @article.comments.create(comment_params)
	    redirect_to article_path(@article)
  end

  # def edit
  #   @comment = Comment.find(params[:id])
  # end

  # def update
  #   @comment = Comment.find(params[:id])

  #   if @comment.update(comment_params)
  #     redirect_to @comment
  #   else
  #     render 'edit'
  #   end
  # end

  def destroy
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    @comment.destroy
    redirect_to article_path(@article)
  end
    private
    	def comment_params
	      params.require(:comment).permit(:commenter, :body)
	    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_form.html.erb
<%= form_for @article  do |f| %>

  <% if @article.errors.any? %>
    <div id="errors">
      <h2>
        <%= pluralize(@article.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :body %><br>
    <%= f.text_area :text %>
  </p>

  <p>
    <%= f.submit %>
  </p>

<% end %>

app/views/articles/index.html.erb
<% @articles.each do |article| %>
	<div class="post_wrapper">
	    <h2 class="title"><%= link_to article.title, article %></h2>
	    <p class="date"> <%= article.created_at.strftime("%B, %d, %Y") %></p>
    </div>
<% end %>
<%= will_paginate @articles, class: "apple_pagination" %>

app/views/articles/new.html.erb
<div id="page_wrapper">
	<h1>New Post</h1>

	<%= render 'form' %>
</div>

app/views/articles/show.html.erb
<div id="post_content">
	<h1 class="title"><%= @article.title %></h1>
	<p class="article-time-info">
		Submitted <%= time_ago_in_words(@article.created_at) %> Ago &nbsp;
	</p>
	<p class= "edit-delete">
		<% if user_signed_in? %>
			<%= link_to 'Edit', edit_article_path(@article) %> |

    		<%= link_to 'Delete', article_path(@article),
                              method: :delete,
                              data: { confirm: 'Are you sure?' } %>
    <% end %>
	</p>
	<p class="body"><%= @article.text %></p>

	<div id="comments">
		<h2> <%= @article.comments.count %> Comments</h2>
		<%= render @article.comments %>

		<h3>Add a comment:</h3>
		<%= render 'comments/form' %>
	</div>
</div>

app/views/comments/_comment.html.erb
<div class="comment clearfix">
	<div class="comment_content">

		<p><strong><%= comment.commenter %></strong></p>

		<p class= "comment-body"><%= comment.body%></p>
		<p class="comment_time"><%= time_ago_in_words(comment.created_at) %> Ago</p>
	</div>

	<p>
		<% if user_signed_in? %>
	 		<%#= link_to 'Edit', edit_comment_path(comment) -%>
			<%= link_to 'Delete Comment', [comment.article, comment],
		               method: :delete,
		               class: "button",
		               data: { confirm: 'Are you sure?' } %>
		<% end %>
    </p>
</div>

app/views/comments/_form.html.erb
<%= form_for([@article, @article.comments.build]) do |f| %>
  <p>
    <%= f.label :commenter %><br>
    <%= f.text_field :commenter %>
  </p>
  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/comments/edit.html.erb
<div id="page_wrapper">
	<h1>Edit article</h1>
	<%= render 'form' %>
	<%= link_to 'Back', articles_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title> <%= yield(:title) %> </title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">

</head>
<body>

<div id="header">
	<div id="cpBtn" onclick="toggleCP()">
		<div></div>
		<div></div>
		<div></div>
	</div>
	<div id="cp">
		<ul class="sidebar-nav">
			<li><%= link_to root_path do %>
					<%= image_tag "logo.png", class: "img-flat" %>
				<% end %>
			</li>
			<li><%= link_to "Blog", root_path %></li>
			<li><%= link_to "New Post", new_article_path %></li>
			<li><%= link_to "About", about_path %></li>
			<li><%= link_to "Contact", contact_path %></li>
			<div class="line"></div>
			</br>
			<li>Connect to me with</li>
			<li><a href="https://twitter.com/rupace10" target="_blank" ><%= image_tag "t.png"  %></a></li>
			<li><a href= 'https://google.com/+RupeshMaharjan1' target="_blank" ><%= image_tag "gplus.png" %></a></li>
			<li><a href="https://linkedin.com/rupace10" target="_blank"><%= image_tag "l.png" %></a></li>
			<li><a href="https://github.com/rupace10" target="_blank"><%= image_tag "github.png" %></a></li>
			<li>
			<p class= "log-in">
			<% if !user_signed_in? %>
					<%= link_to "Login", new_user_session_path %>
				<%#= link_to "Sign up", new_user_registration_path, class: "button" -%>
			<% end %>
			</p>
			</li>
		</ul>
	</div>

	<% if current_page?(root_path)%>
		<p class="ap-text">All Posts</p>
	<% elsif current_page?(about_path)%>
		<p>About</p>
	<% else %>
		<p><%= icon('arrow-left') %> &nbsp; <%= link_to "Back to All Posts", root_path %></p> &nbsp;
	<% end %>

			<%-# if can? :update, @user -%>
				 <%#= link_to "Admin", admin_root_path -%>
			<%-# end -%>

	<% if user_signed_in? %>
	<span class="log-in-as" > Logged in as: <%= current_user.email %>. </span>
		<div class="buttons">
			<%= link_to "Log Out", destroy_user_session_path, :method => :delete, class: "button" %>
			&nbsp;
			<%= link_to 'New Post', new_article_path, class: "button" %>
		</div>
	<% end %>
</div>
<div id="content" class="container">
	<% flash.each do|name, msg| %>
	<%= content_tag(:div, msg, class: "alert") %>
	<% end %>

<%= yield %>

</div>
	<%= javascript_include_tag :defaults %>
	<p><%= notice %></p>
<p><%= alert %></p>
<script>
function toggleCP(){
	var cp = document.getElementById("cp");
	cp.style.height = window.innerHeight - 60+"px";
	if(cp.style.right == "0px"){
		cp.style.right = "-260px";
	}
	else {
		cp.style.right = "0px";
	}
}
</script>
</body>

</html>

app/views/pages/about.html.erb
<% provide(:title, "About Us") %>
<div id="page_wrapper">
	<div id="profile_image">
		<%= image_tag "profile.jpeg" %>
	</div>

	<div id="content">
		<h1>Hey, I'm Rupesh Maharjan</h1>
		<p>This is my first ruby application</p>
		<p></p>
		<p>If you'd like to follow along as I learn more Ruby on Rails, find me on Twitter <a href="http://twitter.com/rupace10">@rupace10</a></p>
	</div>
</div>

app/views/pages/contact.html.erb
<% provide(:title, "Contact") %>
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/home.html.erb
<% provide(:title, "Welcome") %>
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>